### ISSUE TITLE
Why was this port created?

### ISSUE THREAD

**Issue by 0joshuaolson1** [vujadin/OimoHx#3]
I'm just curious why neither of the [other](https://github.com/luboslenco/Oimo/compare/master...tor4kichi:master) [two](https://github.com/tor4kichi/OimoPhysics.haxe/compare/master...luboslenco:master) major ports were used when they were around for several months at the time of OimoHx's first commit.

**Comment by vujadin** [comment]
This one was made for BHx specifically. Not sure if/how it would work with
other engines. The idea was to make it part of BHx as its built-in physics
engine at some point, but its to basic (it lacks features)

**Comment by 0joshuaolson1** [comment]
Oh, okay. Are you instead hoping to use Kha's physics integration?

**Comment by vujadin** [comment]
I would like to implement support for BulletHx eventually, right now I'm experimenting with JigLibHx, also working on CannonJs port to Haxe...

**Comment by 0joshuaolson1** [comment]
All interesting choices. Good luck and if I get far enough with BabylonHx, I may be able to help.
