### ISSUE TITLE
OimoHx and Away3D?

### ISSUE THREAD

**Issue by ramsestom** [vujadin/OimoHx#5]
Hi

  I want to use OimoHx as a physic engine with away3D-openfl (because I couldn't make babylonHx to work correctly so I decided to go with away3D).
However, I can't find any documentation on Oimo... So, before using it, I need to know if it could suit my needs. 
Basically, I have a game which is composed of a ball rolling into a 3D maze (the ball will move according to gravity applied on x,y,z axes) and I want to be able to track when ball hit walls and is rolling (so collide with a floor wall but as a displacement vector parallel to the floor wall plane) to play sounds.
So I need a physic engine that is able to:
- integrate with away3D (take some mesh or vertices list as input to create the 3D body and can easily transfer body movment information to the away3D renderer with some kind of callback to render the scene)
- detect collisions between two objects (a ball and some walls) and to return the 3D coordinates of this collision
- return the velocity of the object (the ball) just before collision so as the normal vector of the collision (to tell if it hit a front wall or if it is just rolling on some floor wall)
- tell is a collision between two objects just started, is ongoing or just stopped 

Do you think this is achievable with OimoHX or do I need to look at another 3D physics engine?
Thanks.

**Comment by vujadin** [comment]
With OimoHx you can do probably all that, not sure about "return the velocity of the object (the ball) just before collision" - for this you'll probably have to measure the distance between bodies yourself, also "tell is a collision between two objects just started, is ongoing or just stopped" - you can definitely detect collision when it happens and you have ContactLink on every rigid body from which you can see with which bodies its in contact. I'm not too familiar with Oimo, just used it in a few demos for BHx.
Have in mind though that this version of Oimo was made specifically to work with BabylonHx and I'm not sure if it will work with other 3D engines (without some changes...).

As far as I know, as3 version of Away3D was using JigLib physics engine and it worked pretty well. So you might try that one, there's a Haxe port of it here https://github.com/luboslenco/jiglibhx

**Comment by ramsestom** [comment]
Thanks for the JigLib link. Would defenitively have a look at it. Thought away3D was using its own physics engine (there is an away-physics but it hasn't been ported to haxe yet) but it might be derived from JigLib... I also found some bullet.js derived engines ported to haxe (Cannon and Ammo) but they are quite old and not developped anymore and the performances of these bullet engines is supposed to be quite poor compared to something more basic like Oimo (That's why I was considering to use at first. Additionaly to the fact that I may switch from away3D to BabylonHx later if I succed to make it work correctly with my haxeflixel project...).
 Will drop you a line if I finally use OimoHx with away3D (just to let you know if it works) ;) . Thanks

**Comment by talvarez75** [comment]
Hi.  I have an openfl away3d haxe project with a vehicle driving around a simple village, but I can't seem to figure out how to add physics, so that the vehicle can angle with the terrain and not drive through walls.  I keep seeing this post in my search attempts.  Did you ever have any luck with using OimoHx or jiglibhx?  I also saw an away3dphysics extern for haxe, but I don't know how to use it.
